{{!--
  # about showtime mobile-user
--}}

{{< layouts/default }}
  {{$classnames}}has-nav-solid about-legal legal-mobile-eula{{/classnames}}

  {{$meta}}
    {{#page}}
      <title>Mobile User Agreement | SHOWTIME </title>
      <meta property="og:title" content="Mobile User Agreement | SHOWTIME" />
      <meta name="description" content="View the SHOWTIME mobile app end user license agreement for use of SHOWTIME mobile applications. " />
      <meta property="og:description" content="View the SHOWTIME mobile app end user license agreement for use of SHOWTIME mobile applications." />
      <meta name="page-tracking" content="sho:about:mobile eula" />
      <meta property="og:image" content="{{meta.valueMap.ogImageUrl}}" />
      <meta name="sho:image" content="{{meta.valueMap.ogImageUrl}}" />
    {{/page}}
  {{/meta}}

  {{$nav}}
    {{< partials/_global_navigation }}
      {{$secondaryNav}}
        {{> about/partials/_legal_secondary_nav}}
      {{/secondaryNav}}
    {{/partials/_global_navigation }}
  {{/nav}}

  {{$content}}
    {{#page}}
      <section class="section section--black section--large legal">
        <h2 class="legal__headline">Mobile App End User License Agreement</h2>

        <p class="legal__body">Effective: November 15, 2018</p>

        <p class="legal__body">THE APPLICATION (AS DEFINED BELOW) YOU ARE DOWNLOADING OR HAVE DOWNLOADED HAS BEEN PROVIDED BY SHOWTIME NETWORKS INC. OR ITS AFFILIATES (COLLECTIVELY, <strong>&quot;SHOWTIME NETWORKS&quot;</strong> or <strong>&quot;we&quot;</strong>).  BY INSTALLING OR USING ALL OR ANY PORTION OF THE APPLICATION, YOU ACCEPT ALL THE TERMS AND CONDITIONS OF THIS END USER LICENSE AGREEMENT (<strong>&quot;AGREEMENT&quot;</strong>).  UPON ACCEPTANCE, THIS AGREEMENT IS ENFORCEABLE AGAINST YOU AND ANY ENTITY THAT OBTAINED THE APPLICATION AND ON WHOSE BEHALF IT IS USED.  IF YOU DO NOT ACCEPT THE TERMS AND CONDITIONS OF THIS AGREEMENT, DO NOT INSTALL OR USE THE APPLICATION.  ACCORDINGLY, YOU AND SHOWTIME NETWORKS AGREE TO THE FOLLOWING:</p>
        <p class="legal__body">The <strong>&quot;Application&quot;</strong> consists of: (a) the Showtime Networks mobile application provided in connection with an authorized link to this Agreement, including all software, code, text, graphics, logos, layouts, designs, interfaces, and other items included in or associated with the application; and (b) any files that are delivered to you by Showtime Networks (via online transmission, through a third party distributor, or otherwise) to patch, update, or otherwise modify the Showtime Networks mobile application.</p>
        <p class="legal__body">The Application may provide a means for you to access one or more websites, other applications, or other products and services offered by Showtime Networks (collectively, the &quot;Services&quot;), and audio and video materials, photographs, text, graphics, logos, layouts, designs, interfaces, software, data and other content associated with the Services (&quot;Content&quot;).  The Application, Services and Content are copyrighted works of Showtime Networks and may contain trademarks, service marks, trade names, and other intellectual property of Showtime Networks.</p>
        <p class="legal__body">The Application and Content, and your use of the Services, are also subject to Showtime Networks&rsquo; <a class="legal__body__link" href="/about/terms">Terms of Use</a>, <a class="legal__body__link" href="https://www.viacomcbsprivacy.com/policy">Privacy Policy</a> and <a class="legal__body__link" href="/about/video-services">Video Services and Social Networking Policy</a> (collectively <strong>&quot;Showtime Networks Terms&quot;</strong>) which are incorporated into this Agreement by this reference.  There may also be additional terms that Showtime Networks presents to you in connection with the Application, for example, at the time of download (<strong>&quot;Additional Terms&quot;</strong>).  If there is a conflict between this Agreement and any Additional Terms, the Additional Terms will control unless the Additional Terms expressly provide otherwise.</p>
        <p class="legal__body">If you are obtaining the Application from a distribution channel such as the Apple App Store or the Android Marketplace (&quot;Distribution Channel&quot;), your purchase, if the application is paid, and any subscription, if the Application or its Content requires a subscription, may be subject to additional terms of the Distribution Channel.  This Agreement is between you and us only, and not with the Distribution Channel.  We, rather than the Distribution Channel, are responsible for the Application and the content thereof.  Neither we nor the Distribution Channel has any obligation to furnish any maintenance and support services with respect to the Application.</p>
        <p class="legal__body">The Application may use location-based services to locate you.  If you choose to use the Application, you consent to Showtime Networks and its third party providers determining your location.</p>
        <p class="legal__body">This Agreement applies to all downloading or installation of the Application after the Effective Date above, and use of any copy of the Application downloaded or installed after the Effective Date above.  Showtime Networks may make changes to this Agreement from time to time by posting a copy of the updated Agreement at <a class="legal__body__link" href="https://www.showtime.com/eula/">https://www.showtime.com/eula</a>.  Changes to this Agreement will be applicable to downloading or installation of the Application after the effective date of the changes.  If you do not agree with any changes to this Agreement, your sole remedy is not to download or install the Application after the effective date of the changes.</p>
        <p class="legal__body">Showtime Networks also may make changes to the Showtime Networks Terms as provided therein.  Such changes will apply to your use of the Application to access Services and Content after the effective date of the changes.  If you do not agree with any such changes, your sole remedy is to discontinue use of the Application to access the relevant Services and Content.  If you continue to use the Application to access Services and Content after the effective date of the changes, you accept all changes.</p>
        <h4 class="legal__sub-headline">1. Disputes; Arbitration</h4>
        <p class="legal__body">If you have any dispute with or claim against us or any of our affiliates (a &quot;Claim&quot;) arising out of or relating to the Application or this Agreement, and the claim is not resolved by calling our customer service department at (877)4-SHOWTIME ((877)474-6984), you and we each agree to resolve such disputes through an individual binding arbitration or an individual action in small claims court.  Class arbitrations and class actions are not permitted, and your Claim may not be consolidated with any other person's claim.  You and we agree that the U.S. Federal Arbitration Act governs the interpretation and enforcement of this provision, and that you and we are each waiving the right to a trial by jury or to participate in a class action.  This Section 12 shall survive termination of this Agreement or any subscription that you may have to receive Content.</p>
        <p class="legal__body">Before you commence an arbitration or file a small claims court action with respect to your Claim, you must first send to Showtime Networks a written notice of your claim (&quot;Notice&quot;).  The Notice must (1) be sent by certified mail; (2) be addressed to: Showtime Networks Inc., 1633 Broadway, New York, NY 10019, Attn: Legal Department; (3) describe the nature of your Claim; and (4) specify the damages or other relief you seek.  If we and you do not then resolve the Claim within 30 days after our receipt of your Notice is received, either you or we may commence an individual binding arbitration or file a small claims court action to resolve the Claim</p>
        <p class="legal__body">Any such arbitration shall be administered by the American Arbitration Association and be conducted in accordance with its Commercial Arbitration Rules, including the Consumer-Related Disputes Supplementary Procedures, if applicable (the &quot;Rules&quot;).  Contact information for the American Arbitration Association, as well as copies of the Rules and applicable forms, are available at <a class="legal__body__link" href="http://www.adr.org">www.adr.org</a>.  In circumstances in which the Rules provide for an in-person hearing, such hearing will, at your request, take place in the U.S. county (or parish) of your residence, or otherwise in Los Angeles, California.  For any non-frivolous Claim that does not exceed &dollar;50,000, Showtime Networks will pay all costs of the arbitration, and reimburse any filing fees you may be required to pay.  You will be responsible for your own legal fees.  If the arbitrator awards you damages that are greater than Showtime Networks' last written settlement offer communicated before commencement of the arbitration, Showtime Networks will pay you the greater of &dollar;1,000 or the amount of the award.</p>
        <h4 class="legal__sub-headline">2. Changes to Product and Service Offerings</h4>
        <p class="legal__body">Showtime Networks or the Distribution Channel may change pricing for the Application, Services and Content.  We may not provide price protection or refunds due to price reductions, promotional pricing, or any other changes to pricing for any reason.</p>
        <p class="legal__body">You acknowledge and agree that Showtime Networks may suspend or discontinue offering the Application; modify the Application; change or discontinue the Services available through the Application; change how we offer and operate such Services (e.g., to begin charging a fee to access features or Content that we previously made available without charge); remove Content; impose limits on certain features or restrict your access to part or all of the Application, Services and Content; or make other changes in Showtime Networks&rsquo; product and service offerings at its sole discretion and with or without notice to you.  We will not be liable to you or any third party for taking any of these actions and we will not be limited to the remedies above if you violate these Showtime Networks Terms.  You further acknowledge and agree that even if a copy of the Application continues to reside on your device, after we make changes in our product or services offerings, the Application may not work as it did prior to such action, and Showtime Networks will have no liability to you or any third party as a result.</p>
        <h4 class="legal__sub-headline">3. Ownership</h4>
        <p class="legal__body">You acknowledge and agree that Showtime Networks has all right, title, and interest in and to the Application and all intellectual property rights associated with the Application.  The Application is protected by the copyright laws of the United States, international treaties and conventions, and other laws.  Except as expressly stated herein, you have no intellectual property rights in the Application (including without limitation any rights to use the trademarks, trade names, service marks, logos, domain names, and other distinctive brand features), and Showtime Networks reserves all rights not expressly granted to you.  You must comply with all laws when using the Application as well as all applicable copyright, trademark or other legal notices or restrictions.</p>
        <p class="legal__body"><strong>You will not: </strong> </p>
          <ul class="legal__body__list">
            <li class="legal__body__list-item">in whole or in part, copy, reproduce, translate, modify, adapt, create derivative works based on, or reverse engineer, derive source code from, disassemble, decompile, or otherwise attempt to discover the source code of, the Application, except to the extent required by applicable law;</li>
            <li class="legal__body__list-item">install or use the Application on a computer or other device that is primarily used as a file server;</li>
            <li class="legal__body__list-item">remove, obscure, or alter any copyright, trademark, logo, or other proprietary notices in or on the Application;</li>
            <li class="legal__body__list-item">use any unauthorized third-party software that intercepts, &quot;mines,&quot; or otherwise collects information from or through the Application, unless authorized by Showtime Networks in its sole discretion;</li>
            <li class="legal__body__list-item">distribute, publish, display, perform, sell, rent, lease, sublicense, assign, transfer, or grant a security interest in your rights in the Application, or authorize all or any portion of the Application to be copied onto another user&rsquo;s computer except as permitted hereunder;</li>
            <li class="legal__body__list-item">intercept, emulate, or redirect the communication protocols used by the Application in any way, for any purpose, or engage in any activity that interferes with or disrupts the Application or Showtime Networks&rsquo; or its vendors&rsquo; servers or other infrastructure; or</li>
            <li class="legal__body__list-item">facilitate, create, or maintain any unauthorized connection to the Application, including without limitation: (a) any connection to any unauthorized server that emulates, or attempts to emulate, Showtime Networks&rsquo; or its vendors&rsquo; servers; and (b) any connection using programs or tools not approved by Showtime Networks in its sole discretion.</li>
            <li class="legal__body__list-item">The Services and Content accessible through the Application are also protected by intellectual property and other laws in the U.S. and in other countries, and are subject to limitations on your use thereof, as set forth more fully in the Showtime Networks Terms.</li>
          </ul>

        <h4 class="legal__sub-headline">4. Grant of a Limited Use License</h4>
         <p class="legal__body">Subject to your compliance with the Showtime Networks Terms and this Agreement, Showtime Networks hereby grants, and you hereby accept, a limited, non-exclusive license to: (a) install the Application on one mobile device owned by you or under your legitimate control; and (b) engage in non-commercial use of the Application.  All rights to use the Application are granted on the condition that such rights are forfeited if you fail to comply with the terms of this Agreement.</p>
        <h4 class="legal__sub-headline">5. Use of the Application</h4>
        <p class="legal__body">When you use the Application, you may connect to Showtime Networks&rsquo; or its vendors&rsquo; servers.  Your communication with Showtime Networks&rsquo; properties is governed by the Showtime Networks Privacy Policy, available at https://sho.com/privacy.  You consent to our use of data that you provide or that we may collect about you through the Application, in compliance with the Privacy Policy.</p>
        <p class="legal__body">As part of the Application, you may receive push notifications, text messages, MMS messages or other types of messages directly sent to you outside or inside the Application (collectively, <strong>"Push Messages"</strong>).  You may control the Push Messages in your device&rsquo;s or the Application&rsquo;s settings.  Some of the Push Messages may be related to your location or to your use of the Application or Content.  Your carrier may charge standard messaging, data and other fees for use of Push Messages, and these fees may appear on your mobile bill or be deducted from your pre-paid balance.  Your carrier may prohibit or restrict certain Push Messages and certain Push Messages may be incompatible with your carrier or mobile device.  Contact your carrier with questions regarding these issues.  You may discontinue Push Messages in your device&rsquo;s or the Application&rsquo;s settings or by deleting the Application.  We may collect information related to your use of Push Messages.  If you have registered for Push Messages, you agree to notify Showtime Networks of any changes to your mobile number, as applicable, and update your account on the Application to reflect this change.</p>
        <p class="legal__body">The Application may allow you to access and interoperate with third party properties, software applications, and data services (collectively, &quot;Third Party Properties&quot;).  Showtime Networks does not control any Third Party Properties to which you may connect using the Application and is not responsible for the practices of any third party.  You acknowledge and agree that Showtime Networks is not liable for any loss or damage which may be incurred by you as a result of any reliance placed by you on the completeness, accuracy, or existence of any advertising, products, or other materials on or available from Third Party Properties.  You acknowledge that the Application may check for updates to the Application that may be available to you.</p>
        <h4 class="legal__sub-headline">6. Warranty Disclaimer</h4>
        <p class="legal__body">SHOWTIME NETWORKS DOES NOT WARRANT: (1) THAT THE APPLICATION&rsquo;S FUNCTIONS OR ANY SERVICES OR CONTENT WILL BE UNINTERRUPTED OR FREE OF ERRORS OR OMISSIONS; (2) THAT DEFECTS WILL BE CORRECTED; (3) THAT THE APPLICATION OR THE SERVERS HOSTING CONTENT ARE FREE OF VIRUSES OR OTHER HARMFUL CODE; OR (4) THAT THE APPLICATION OR SERVICES OR CONTENT AVAILABLE THROUGH THE APPLICATION WILL CONTINUE TO BE AVAILABLE.  SHOWTIME NETWORKS SHALL HAVE NO LIABILITY FOR ANY SUCH ISSUES.  SHOWTIME NETWORKS AND THE DISTRIBUTION CHANNEL DISCLAIM ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, NONINFRINGEMENT, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUALITY, AVAILABILITY AND AS TO SUBJECT MATTER OF CONTENT.  THE APPLICATION, SERVICES AND CONTENT ARE PROVIDED &quot;AS IS,&quot; &quot;AS AVAILABLE,&quot; AND &quot;WITH ALL FAULTS.&quot;</p>
        <p class="legal__body">YOUR ACCESS TO AND USE OF THE APPLICATION IS AT YOUR RISK.  IF YOU ARE DISSATISFIED WITH THE APPLICATION OR ANY OF THE SERVICES OR CONTENT AVAILABLE THROUGH THE APPLICATION, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE ACCESSING AND USING THE APPLICATION.</p>
        <p class="legal__body">The Distribution Channel will not be responsible for addressing any claims by you or any third party relating to the Application or your possession and/or use of the Application, including: (i) product liability claims; (ii) any claim that the Application fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation. If you have any questions on those issues, you should contact us at the address below.  The Distribution Channel will also not be responsible for investigation, defense, settlement and discharge of any third party intellectual property infringement claim.</p>
        <h4 class="legal__sub-headline">7. Limitation of Liability/Release of Claims</h4>
        <p class="legal__body">SHOWTIME NETWORKS WILL NOT BE LIABLE FOR ANY FAILURE OR DELAY IN THEIR PERFORMANCE DUE TO ANY CAUSE BEYOND THEIR REASONABLE CONTROL, INCLUDING ACTS OF WAR, ACTS OF GOD, ACTS OF THIRD PARTY SERVICE PROVIDERS, EARTHQUAKE, FLOOD, EMBARGO, RIOT, SABOTAGE, LABOR SHORTAGE OR DISPUTE, GOVERNMENTAL ACT, POWER FAILURE OR FAILURE OF THE INTERNET OR COMPUTER EQUIPMENT.</p>
        <p class="legal__body">SHOWTIME NETWORKS WILL NOT BE LIABLE TO YOU OR ANYONE ELSE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, EXEMPLARY, PUNITIVE OR CONSEQUENTIAL DAMAGES IN CONNECTION WITH THE APPLICATION (INCLUDING THE SERVICES AND CONTENT AVAILABLE THROUGH THE APPLICATION) OR THIS AGREEMENT, EVEN IF FORESEEABLE OR EVEN IF SHOWTIME NETWORKS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES (INCLUDING, WITHOUT LIMITATION, WHETHER CAUSED IN WHOLE OR IN PART BY NEGLIGENCE, GROSS NEGLIGENCE, OR OTHERWISE, BUT EXCLUDING WILLFUL MISCONDUCT).  IN NO EVENT WILL SHOWTIME NETWORKS&rsquo; LIABILITY FOR OTHER DAMAGES EXCEED THE AMOUNT PAID BY YOU TO ACQUIRE THE APPLICATION.  THE FOREGOING LIMITATIONS WILL APPLY EVEN IF ANY STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>
        <p class="legal__body">YOU ACKNOWLEDGE AND AGREE THAT IF YOU INCUR ANY DAMAGES THAT ARISE OUT OF SHOWTIME NETWORKS&rsquo; ACTS OR OMISSIONS, THE DAMAGES, IF ANY, ARE NOT IRREPARABLE AND ARE NOT SUFFICIENT TO ENTITLE YOU TO AN INJUNCTION OR OTHER EQUITABLE RELIEF RESTRICTING EXPLOITATION OF ANY WEBSITE, PROPERTY, PRODUCT, PROGRAM, TELEVISION SHOW, MOTION PICTURE, OR OTHER AUDIO/VISUAL CONTENT OWNED, CONTROLLED, OR DISTRIBUTED BY SHOWTIME NETWORKS, INCLUDING WITHOUT LIMITATION THE APPLICATION.</p>
        <p class="legal__body">SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO SOME OF THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
        <h4 class="legal__sub-headline">8. Indemnity</h4>
        <p class="legal__body">You will indemnify, defend, and hold Showtime Networks and all of its officers, directors, owners, employees, agents, information providers, service providers, vendors, contractors, affiliates, partners, and licensors (collectively, the <strong>&quot;Showtime Networks Parties&quot;</strong>) harmless from and against any and all liability, losses, costs, and expenses (including attorneys&rsquo; fees) incurred by any of the Showtime Networks Parties in connection with any claim, including, but not limited to, claims for defamation, violation of rights of publicity or privacy, copyright infringement, or trademark infringement arising out of: your use of the Application; any use or alleged use of your account or your passwords by any person, whether or not authorized by you; your connection to Showtime Networks&rsquo; or its vendors&rsquo; servers; your violation of this Agreement; or your violation of the rights of any other person or entity.  Showtime Networks reserves the right, at its own expense, to assume the exclusive defense and control of any matter for which you are required to indemnify Showtime Networks, and you will cooperate with Showtime Networks&rsquo; defense of these claims.</p>
        <h4 class="legal__sub-headline">9. Termination</h4>
        <p class="legal__body">This Agreement is effective until terminated.  You may terminate this Agreement at any time by: (i) irretrievably erasing, deleting, or destroying all copies of the Application in your possession or control; and (ii) ceasing to use the Services and Content available through the Application.  Showtime Networks may terminate this Agreement at any time for any reason or no reason.  However, if you paid Showtime Networks or its authorized Distribution Channel to acquire the Application, and we terminate this Agreement within one year after you made your payment for reasons other than your breach of this Agreement or the Showtime Networks Terms, we will refund a prorated portion of the purchase price corresponding to the portion of such one year period for which our action caused you not to be able to use the Application.  Upon termination for any reason, the license granted in Section 4 will immediately terminate.  The provisions in Sections 1, 2, 3, 5, 6, 7, 8, 11, and 12 will survive any termination.</p>
        <h4 class="legal__sub-headline">10. Export Controls</h4>
        <p class="legal__body">You will not ship, transfer, or export the Application into any country or use the Application in any manner prohibited by the United States Export Administration Act or any other export laws, restrictions, or regulations (collectively, <strong>&quot;Export Laws&quot;</strong>).  You represent and warrant that you are not a citizen of, and are not located within, a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a &quot;terrorist supporting&quot; country, and that you are not otherwise prohibited under the Export Laws from receiving the Application.</p>
        <h4 class="legal__sub-headline">11. Governing Law, Venue, and Jurisdiction</h4>
        <p class="legal__body">This Agreement and all claims arising from or related to your use of the Application will be governed by and construed in accordance with the laws of the State of California, except California&rsquo;s conflict of law rules.  This Agreement and the Application will not be governed by the United Nations Convention on Contracts for the International Sale of Goods, if applicable. With respect to any disputes or claims not subject to arbitration (as set forth below), you agree to exclusive jurisdiction in the state and federal courts in Los Angeles, California.  Notwithstanding any other provision of this Agreement, we may seek injunctive or other equitable relief from any court of competent jurisdiction.
        </p>
        <p class="legal__body">Regardless of any statute or law to the contrary, you must file any claim or action related to use of the Application or this Agreement within one year after such claim or action accrued. Otherwise, you will waive the claim or action.</p>
        <h4 class="legal__sub-headline">12. Miscellaneous</h4>
        <p class="legal__body">This Agreement constitutes the entire agreement between the parties with respect to its subject matter and supersedes any prior oral or written agreements, provided, however, that this Agreement will coexist with the Showtime Networks Terms and any Additional Terms.  To the extent that the provisions of this Agreement conflict with the Showtime Networks Terms, this Agreement will govern.  We may be required by state or federal law to notify you of certain events.  You hereby acknowledge and agree that such notices will be effective upon our posting them on our sites or delivering them to you via email, if you have provided it to us.  If you do not provide us with accurate information or we do not have access to your email address, we will not be responsible for failure to notify you.  If any part of this Agreement is determined to be invalid or unenforceable under applicable law, that provision will be removed, and the remainder of the Agreement will continue to be valid and enforceable, except as expressly stated.  Our failure to exercise or enforce any right or provision in this Agreement will not constitute a waiver of such right or provision.  Except as otherwise required by law, the controlling language of this Agreement is English.  This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.  You and we acknowledge and agree that the Distribution Channel and its subsidiaries are intended third party beneficiaries of this Agreement and will have the right (and will be deemed to have accepted the right) to enforce this Agreement against you.</p>
        <h4 class="legal__sub-headline">13. Contact Information</h4>
        <p class="legal__body">You may contact Showtime Networks at:<br><br>
            Showtime Networks Inc.<br>
            1633 Broadway<br>
            New York, NY  10019
          </p>
        <p class="legal__body">If you have any questions, claims, or complaints, you should notify us through the contact or help feature of the relevant Service.</p>
        <p class="legal__body">You hereby acknowledge that you have read and understood this Agreement and agree that by clicking <strong>&quot;Accept&quot;</strong> or by installing, copying, or using the Application you are acknowledging your agreement to be bound by this Agreement.</p>
      </section>


      {{#popularSeriesGroup}}
        {{> series/partials/_series_slider}}
      {{/popularSeriesGroup}}
    {{/page}}
  {{/content}}
{{/ layouts/default}}
