{{!--
  # about showtime terms
--}}

{{< layouts/default }}
  {{$classnames}}has-nav-solid about-legal legal-terms {{/classnames}}

  {{$meta}}
    {{#page}}
      <title>Terms of Use | SHOWTIME</title>
      <meta property="og:title" content="Terms of Use | SHOWTIME" />
      <meta name="description" content="Review the terms of use for the SHOWTIME websites, mobile and connected TV applications. " />
      <meta property="og:description" content="Review the terms of use for the SHOWTIME websites, mobile and connected TV applications. " />
      <meta name="page-tracking" content="sho:about:terms" />
      <meta property="og:image" content="{{meta.valueMap.ogImageUrl}}" />
      <meta name="sho:image" content="{{meta.valueMap.ogImageUrl}}" />
    {{/page}}
  {{/meta}}

  {{$nav}}
    {{< partials/_global_navigation }}
      {{$secondaryNav}}
        {{> about/partials/_legal_secondary_nav}}
      {{/secondaryNav}}
    {{/partials/_global_navigation }}
  {{/nav}}

  {{$content}}
    {{#page}}
    <section class="section section--black section--large legal">

      <h2 class="legal__headline">Terms of Use</h2>

      <p class="legal__body">Effective Date January 12, 2023</p>
      <p class="legal__body">Welcome to the network of interactive services provided by Showtime Networks Inc. or its affiliates (collectively, &quot;Provider,&quot; &quot;Showtime Networks,&quot; &quot;us,&quot; or &quot;we&quot;). These Terms of Use, including the  <a class="legal__body__link" href="#disputes-arbitration">&quot;Dispute Resolution; Arbitration Agreement&quot; provisions </a> in Section 1 below (&quot;Terms&quot;), govern your use of the websites, mobile and connected TV applications, features, products and services that include an authorized link to these Terms (collectively, the &quot;Services&quot;).</p>

      <p class="legal__body">Please review these Terms carefully before using the Services because they affect your rights.  By using any of the Services, you accept these Terms and agree to be legally bound by them.</p>

      <p class="legal__body">Please consult our <a class="legal__body__link" href="https://www.viacomcbsprivacy.com/policy">Privacy Policy</a> for information regarding our privacy practices.</p>

      <p class="legal__body">Certain provisions of these Terms apply only to specified Services.  For example, special provisions applicable to the Showtime standalone streaming service (the &quot;Streaming Service&quot;) are contained in Section 8, and special provisions applicable to Showtime Anytime are contained in Section 9.  If you are a user of either of those Services, those sections apply to you, in addition to other provisions of these Terms.  References to Services throughout these Terms include the Streaming Service and Showtime Anytime.</p>

      <p class="legal__body" id="disputes-arbitration">These Terms are effective as of the Effective Date above. If you have not reviewed the Terms of Use applicable to a Service since the Effective Date, please review these updated Terms carefully before using any Service.</p>

      <p class="legal__body">We may change these Terms in the future, so we encourage you to review periodically the Terms of Use applicable to each Service you use. The most current version of the applicable Terms of Use (along with its effective date) will be linked from each of the Services. Changes to these Terms will be effective immediately or, if required by law, 30 days after notice to you, which may be given by posting the updated Terms on our Services or by electronic or conventional mail. If you do not agree with any changes to these Terms, your sole remedy is not to use the Services.
      If you continue to use the Services after we change these Terms, you accept all changes.</p>

      <h4 class="legal__sub-headline">1. Dispute Resolution; Arbitration Agreement</h4>

      <p class="legal__body">IF YOU OR WE HAVE ANY DISPUTE WITH OR CLAIM AGAINST THE OTHER (A &quot;CLAIM&quot;) ARISING OUT OF OR RELATING IN ANY WAY TO THE SERVICES OR THESE TERMS, AND THE CLAIM IS NOT RESOLVED BY CALLING OUR CUSTOMER CARE DEPARTMENT AT (877)4-SHOWTIME ((877)474-6984) OR BY FOLLOWING THE INFORMAL DISPUTE RESOLUTION PROCEDURE SET FORTH BELOW, YOU AND WE EACH AGREE TO RESOLVE SUCH DISPUTES THROUGH AN INDIVIDUAL BINDING ARBITRATION OR AN INDIVIDUAL ACTION IN SMALL CLAIMS COURT. Class arbitrations and class actions are not permitted, and a Claim may not be consolidated with any other person's claim. You and we agree that the U.S. Federal Arbitration Act governs the interpretation and enforcement of this provision, and that you and we are each waiving the right to a trial by jury or to participate in a class action. You and we agree that any arbitrations between you and us will be subject to this Section 1 and not to any prior arbitration agreement you had with us. This Section 1 shall survive termination of these Terms or any subscription that you may have to any of the Services.</p>

      <p class="legal__body">1.1 Mandatory Pre-Arbitration Notice and Informal Dispute Resolution Procedure. Before a party commences an arbitration or files a small claims court action with respect to a Claim, the party must first send to the other a written notice of dispute (&quot;Notice&quot;). A Notice from you to us must (1) be sent by certified mail; (2) be addressed to: Showtime Networks Inc., 1633 Broadway, New York, NY 10019, Attn: Legal Department; (3) contain your name, address, and email address; (4) describe the nature and basis of your Claim; (5) if you are submitting the Notice, include any relevant facts regarding your use of the Services, including without limitation whether you have created an account; (6) specify the nature and basis of the specific relief sought, including the damages sought, if any, and a detailed calculation of them; and (7) include a personally signed statement from you (and not your counsel) verifying the accuracy of the contents of the Notice. The Notice must be individualized, meaning it can concern only your dispute and no other person's dispute.</p>

      <p class="legal__body">After receipt of a completed Notice, the parties shall engage in a good faith effort to resolve the dispute for a period of 60 days (which can be extended by agreement). You and we agree that, after receipt of the completed Notice, the recipient may request an individualized telephone or video settlement conference (which can be held after the 60-day period) and both parties will personally attend (with counsel, if represented). You and we agree that the parties (and counsel, if represented) shall work cooperatively to schedule the conference at the earliest mutually-convenient time and to seek to reach a resolution. If we and you do not reach an agreement to resolve the issues identified in the Notice within 60 days after the completed Notice is received (or a longer time if agreed to by the parties), you or we may commence an arbitration proceeding or a small claims court proceeding (if permitted by small claims court rules).</p>

      <p class="legal__body">Compliance with this Mandatory Pre-Arbitration Notice and Informal Dispute Resolution Procedures section is a condition precedent to initiating arbitration. Any applicable limitations period (including statute of limitations) and any filing fee deadlines shall be tolled while the parties engage in the informal dispute resolution procedures set forth in this Subsection 1.1. All of the Mandatory Pre-Arbitration Notice and Informal Dispute Resolution Procedures are essential so that you and we have a meaningful opportunity to resolve disputes informally. If any aspect of these requirements has not been met, a court of competent jurisdiction may enjoin the filing or prosecution of an arbitration. In addition, unless prohibited by law, the arbitration administrator may not accept, administer, assess, or demand fees in connection with an arbitration that has been initiated without completion of the Mandatory Pre-Arbitration Notice and Informal Dispute Resolution Procedure. If the arbitration is already pending, it shall be administratively closed. Nothing in this paragraph limits the right of a party to seek damages for non-compliance with this Procedure in arbitration.</p>

      <p class="legal__body">1.2 Arbitration Procedure. Any such arbitration shall be governed by applicable rules of National Arbitration & Mediation (&quot;NAM&quot;) (including the <a class="legal__body__link" href="https://www.namadr.com/content/uploads/2022/04/Comprehensive-Rules-as-of-4.18.2022.pdf">Comprehensive Dispute Resolution Rules and Procedures</a> and/or the <a class="legal__body__link" href="https://www.namadr.com/content/uploads/2021/12/SupplementalRules12.22.21.pdf">Supplemental Rules for Mass Arbitration Filings</a>, as applicable) (&quot;NAM Rules&quot;), as modified by this Arbitration Agreement, and will be administered by NAM. (If NAM is unavailable or unwilling to do so, another arbitration provider shall be selected by the parties that will do so, or if the parties are unable to agree on an alternative administrator, by the court pursuant to 9 U.S.C. §5.) The NAM Rules are available online at www.NAMADR.com, by calling NAM at 1-800-358-2550, or by requesting them in writing at the Notice Address. You may obtain a form to initiate arbitration at: <a class="legal__body__link" style="word-break:break-all;" href="https://www.namadr.com/content/uploads/2020/09/Comprehensive-Demand-for-Arb-revised-9.18.19.pdf">https://www.namadr.com/content/uploads/2020/09/Comprehensive-Demand-for-Arb-revised-9.18.19.pdf</a> or by contacting NAM.</p>

      <p class="legal__body">You and we agree that the party initiating arbitration must submit a certification that they have complied with and completed the Mandatory Pre-Arbitration Notice and Informal Dispute Resolution Procedures requirements referenced in Subsection 1.1 and that they are a party to the Arbitration Agreement enclosed with or attached to the demand for arbitration. The demand for arbitration and certification must be personally signed by the party initiating arbitration (and their counsel, if represented). </p>

      <p class="legal__body">All issues, including the scope and enforceability of this Arbitration Agreement, are for the arbitrator to decide. The arbitrator may consider but shall not be bound by rulings in other arbitrations involving different customers. At the conclusion of the arbitration proceeding, the arbitrator shall issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the award is based. The arbitrator's decision is binding only between you and us and will not have any preclusive effect in another arbitration or proceeding that involves a different party. An arbitrator's award that has been fully satisfied shall not be entered in any court.</p>

      <p class="legal__body">As in court, you and we agree that any counsel representing a party in arbitration certifies when initiating and proceeding in arbitration that they are complying with the requirements of Federal Rule of Civil Procedure 11(b), including certification that the claim or relief sought is neither frivolous nor brought for an improper purpose. The arbitrator is authorized to impose any sanctions under the NAM Rules, Federal Rule of Civil Procedure 11, or applicable federal or state law, against all appropriate represented parties and counsel.</p>

      <p class="legal__body">Except as expressly provided in this Arbitration Agreement, the arbitrator may grant any remedy, relief, or outcome that the parties could have received in court, including awards of attorneys' fees and costs, in accordance with applicable law. Unless otherwise provided by applicable law, the parties shall bear their own attorneys' fees and costs in arbitration unless the arbitrator awards sanctions or finds that either the substance of the claim, the defense, or the relief sought is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b).</p>

      <p class="legal__body">The payment of arbitration fees (the fees imposed by the arbitration administrator including filing, arbitrator, and hearing fees) will be governed by the applicable NAM Rules, unless you qualify for a fee waiver under applicable law.</p>

      <p class="legal__body">In circumstances in which the NAM Rules provide for an in-person hearing, such hearing will take place in the U.S. county (or parish) of your residence, or otherwise in New York, New York. If the Mass Filing process described in Subsection 1.7 is triggered, then the location of any hearing will be determined by the arbitrator.</p>

      <p class="legal__body">1.3 Discovery During Arbitration. The parties shall each be limited to a maximum of one (1) fact witness deposition per side, unless the arbitrator determines that more depositions are warranted based on the totality of circumstances, including the amount in controversy, the complexity of the factual issues, the number of parties and the diversity of their interests, and whether any or all of the claims appear, on the basis of the pleadings, to have sufficient merit to justify the time and expense associated with the requested discovery. Document requests shall be limited to documents that are directly relevant to the matter(s) in dispute or to its outcome; shall be reasonably restricted in terms of time frame, subject matter and persons or entities to which the requests pertain; shall not include broad phraseology such as &quot;all documents directly or indirectly related to&quot;; and shall not be encumbered with extensive &quot;definitions&quot; or &quot;instructions.&quot; The Arbitrator may edit or limit the number of document requests based on the totality of circumstances, including the factors listed above.</p>

      <p class="legal__body">Electronic discovery, if any, shall be limited as follows. Absent a showing of compelling need: (i) electronic documents shall only be produced from sources used in the ordinary course of business, and not from backup servers, tapes or other media; (ii) the production of electronic documents shall normally be made on the basis of generally available technology in a searchable format that is usable by the requesting party and convenient and economical for the producing party; (iii) the parties need not produce metadata, with the exception of header fields for email correspondence; (iv) the description of custodians from whom electronic documents may be collected should be narrowly tailored to include only those individuals whose electronic documents may reasonably be expected to contain evidence that is material to the dispute; and (v) where the costs and burdens of e-discovery are disproportionate to the nature of the dispute or to the amount in controversy, or to the relevance of the materials requested, the arbitrator may either deny such requests or order disclosure on the condition that the requesting party advance the reasonable cost of production to the other side, subject to the allocation of costs in the final award. </p>

      <p class="legal__body">1.4 Confidentiality. Upon either party's request, the arbitrator will issue an order requiring that confidential information of either party disclosed during the arbitration (whether in documents or orally) may not be used or disclosed except in connection with the arbitration or a proceeding to enforce the arbitration award and that any permitted court filing of confidential information must be done under seal to the furthest extent permitted by law.</p>

      <p class="legal__body">1.5 Offer of Settlement. In any arbitration between you and us, the defending party may, but is not obligated to, make a written settlement offer at any time before the evidentiary hearing or, if a dispositive motion is permitted, prior to the dispositive motion being granted. The amount or terms of any settlement offer may not be disclosed to the arbitrator until after the arbitrator issues an award on the claim. If the award is issued in the other party's favor and is less than the defending party's settlement offer or if the award is in the defending party's favor, the other party must pay the defending party's costs incurred after the offer was made, including any attorney's fees. If any applicable statute or case law prohibits the shifting of costs incurred in the arbitration, then the offer in this provision shall serve to cease the accumulation of any costs to which the party bringing the claim may be entitled for the cause of action under which it is suing.</p>

      <p class="legal__body">1.6 Opt Out of Future Changes. Notwithstanding any provision to the contrary, if we make any future change to this Arbitration Agreement (other than a change to the Notice Address), you may reject any such change by sending us an opt out notice via certified mail addressed to Showtime Networks Inc., 1633 Broadway, New York, NY 10019, Attn: Legal Department which includes: (i) your full legal name, (ii) your complete mailing address, (iii) your phone number, (iv) if applicable, the username or email address associated with any potential account; and (v) the approximate date of your initial use of the Services. Such an opt-out notice must be sent by you personally, and not by your agent, attorney, or anyone else purporting to act on your behalf. It must include a statement, personally signed by you, that you wish to reject the change to the Arbitration Agreement. This is not an opt out of arbitration altogether.</p>

      <p class="legal__body">1.7 Mass Filing. If, at any time, 25 or more claimants (including you) submit Notices or seek to file demands for arbitration raising similar claims against the other party or related parties by the same or coordinated counsel or entities, consistent with the definition and criteria of Mass Filings (&quot;Mass Filing&quot;) set forth in NAM's Mass Filing Supplemental Dispute Resolution Rules and Procedures (&quot;NAM's Mass Filing Rules,&quot; available at <a class="legal__body__link" href="https://www.namadr.com/resources/rules-fees-forms/"> https://www.namadr.com/resources/rules-fees-forms/</a>), you and we agree that the additional procedures set forth below shall apply. The parties agree that throughout this process, their counsel shall meet and confer to discuss modifications to these procedures based on the particular needs of the Mass Filing. The parties acknowledge and agree that by electing to participate in a Mass Filing, the adjudication of their dispute might be delayed. Any applicable limitations period (including statute of limitations) and any filing fee deadlines shall be tolled beginning when the Mandatory Pre-Arbitration Notice and Informal Dispute Resolution Procedures are initiated, so long as the pre-arbitration Notice complies with the requirements in Subsection 1.1, until your claim is selected to proceed as part of a staged process or is settled, withdrawn, otherwise resolved, or opted out of arbitration.</p>

      <p class="legal__body">Stage One: Counsel for the claimants and counsel for Showtime Networks shall each select 25 claims per side (50 claims total) to be filed and to proceed in individual arbitrations as part of a staged process. Each of these individual arbitrations shall be assigned to a different, single arbitrator unless the parties agree otherwise in writing. Any remaining claims shall not be filed or be deemed filed in arbitration, nor shall any arbitration fees be assessed in connection with those claims unless and until they are selected to be filed in individual arbitration proceedings as part of a staged process. After this initial set of staged proceedings is completed, the parties shall promptly engage in a global mediation session of all remaining claims with a retired federal or state court judge and Showtime Networks shall pay the mediator's fee.</p>

      <p class="legal__body">Stage Two: If the remaining claims are not resolved at this time, counsel for the claimants and counsel for Showtime Networks shall each select 50 claims per side (100 claims total) to be filed and to proceed in individual arbitrations as part of a second staged process, subject to any procedural changes the parties agreed to in writing. Each of these individual arbitrations shall be assigned to a different, single arbitrator unless the parties agree otherwise in writing. Any remaining claims shall not be filed or be deemed filed in arbitration, nor shall any arbitration fees be assessed in connection with those claims unless and until they are selected to be filed in individual arbitration proceedings as part of a staged process. After this second set of staged proceedings is completed, the parties shall promptly engage in a global mediation session of all remaining claims with a retired federal or state court judge and Showtime Networks shall pay the mediator's fee.</p>

      <p class="legal__body">Stage Three: If the remaining claims are not resolved at this time, counsel for the claimants and counsel for Showtime Networks shall each select 100 claims per side (200 claims total) to be filed and to proceed in individual arbitrations as part of a third staged process, subject to any procedural changes the parties agreed to in writing. Any remaining claims shall not be filed or be deemed filed in arbitration, nor shall any arbitration fees be assessed in connection with those claims unless and until they are selected to be filed in individual arbitration proceedings as part of a staged process. Following this third set of staged proceedings, counsel for claimants may elect to have the parties participate in a global mediation session of all remaining claims with a retired federal or state court judge.</p>

      <p class="legal__body">If your claim is not resolved as part of the staged process identified above, either:</p>
      <p class="legal__body">Option One: You and Showtime Networks may separately or by agreement, opt out of arbitration and elect to have your claim heard in court consistent with these Terms. You may opt out of arbitration by sending Showtime Networks your individual, personally signed notice of your intention to opt out by certified mail addressed to Showtime Networks Inc., 1633 Broadway, New York, NY 10019, Attn: Legal Department. Such an opt-out notice must be sent by you personally, and not by your agent, attorney, or anyone else purporting to act on your behalf. It must include a statement, personally signed by you, that you wish to opt out of arbitration within 30 days after the conclusion of Stage 3 or the elective mediation associated with Stage 3. Showtime Networks may opt your claim out of arbitration by sending an individual, personally signed notice of its intention to opt out to your counsel within 14 days after the expiration of your 30 day opt out period. Counsel for the parties may agree to adjust these deadlines.</p>

      <p class="legal__body">OR</p>
      <p class="legal__body">Option Two: If neither you nor Showtime Networks elect to have your claim heard in court consistent with Option One, then you agree that your claim will be resolved as part of continuing, staged individual arbitration proceedings as set forth below. Assuming the number of remaining claims exceeds 200, then 200 claims shall be randomly selected (or selected through a process agreed to by counsel for the parties) to be filed and to proceed in individual arbitrations as part of a staged process. If the number of remaining claims is fewer than 200, then all of those claims shall be filed and proceed in individual arbitrations. Any remaining claims shall not be filed or be deemed filed in arbitration, nor shall any arbitration fees be assessed in connection with those claims unless and until they are selected to be filed in individual arbitration proceedings as part of a staged process. After each set of 200 claims are adjudicated, settled, withdrawn, or otherwise resolved, this process shall repeat consistent with these parameters. Counsel for the parties are encouraged to meet and confer, participate in mediation, and engage with each other and with NAM (including through a Procedural Arbitrator) to explore ways to streamline the adjudication of claims, increase the number of claims to proceed at any given time, promote efficiencies, conserve resources, and resolve the remaining claims.</p>

      <p class="legal__body">A court of competent jurisdiction shall have the authority to enforce these Mass Filing provisions and, if necessary, to enjoin the mass filing, prosecution, or administration of arbitrations and the assessment of arbitration fees. If these additional procedures apply to your claim, and a court of competent jurisdiction determines that they are not enforceable as to your claim, then your claim shall proceed in a court of competent jurisdiction consistent with these Terms. </p>

      <p class="legal__body">You and Showtime Networks agree that we each value the integrity and efficiency of arbitration and wish to employ the process for the fair resolution of genuine and sincere disputes between us. You and Showtime Networks acknowledge and agree to act in good faith to ensure the processes set forth herein are followed. The parties further agree that application of these Mass Filing procedures have been reasonably designed to result in an efficient and fair adjudication of such cases.</p>

      <p class="legal__body">1.8 Severability. If any portion of this Arbitration Agreement is found to be void, invalid, or otherwise unenforceable, then that portion shall be deemed to be severable and, if possible, superseded by a valid, enforceable provision, or portion thereof, that matches the intent of the original provision, or portion thereof, as closely as possible. The remainder of this Arbitration Agreement shall continue to be enforceable and valid according to the terms contained herein.</p>

      <h4 class="legal__sub-headline">2. Privacy Policy; Additional Terms</h4>
      <p class="legal__body">Our <a class="legal__body__link" href="https://www.viacomcbsprivacy.com/policy">Privacy Policy</a> describes our practices concerning data that you provide or that we may collect about you through the Services.</p>


      <p class="legal__body">Additional terms may apply to your use of certain Services, including features of our Services that are provided by third parties. These terms will be provided to you or posted on the Services to which they apply, and they are incorporated by reference into these Terms. If there is a conflict between these Terms and any additional terms that apply to a particular Service, the additional terms will control.</p>

      <p class="legal__body">Sweepstakes, contests, and promotions on the Services may also have additional rules and eligibility requirements, such as certain age or geographic area restrictions. You are responsible for complying with these rules and requirements.
      </p>

      <h4 class="legal__sub-headline">3. Access to the Services: Territory, Age, Registration and Access Controls</h4>
      <p class="legal__body">The Services are intended solely and exclusively for residents of the United States, its territories and possessions ("U.S.") while they are located in the U.S. Use of and registration for the Services are void where prohibited. We may use technology to limit access to the Services from outside the U.S. Your location may not be identified accurately by the technology we use, so you may be unable to access the Services or parts thereof even if you are located in an area in which we intend to provide access. You consent to Provider and its third party providers determining your location for purposes of providing the Services. Software available in connection with Services may be subject to U.S. export control laws. You agree not to export or re-export such software in violation of U.S. export control laws.</p>

      <p class="legal__body">To access and use our connected TV applications that do not incorporate the linear feed of SHOWTIME, you must be at least 14 years of age. All of our other Services are designed for and targeted to adults. They may contain certain content that may not be appropriate for children or that you might find objectionable. To access and use any such Services, you must be at least 18 years of age (or whatever the applicable age of majority (legal adulthood) is where you are located), unless you are a registered sub-account holder in a household with access to Showtime Anytime and you are accessing Showtime Anytime with the permission of your parent or guardian that is the primary account holder, as described in Section 9. It is your sole responsibility to determine whether the content in the Services is suitable for you.</p>

      <p class="legal__body">By using the Services, you certify that you meet applicable eligibility requirements. </p>

      <p class="legal__body">If we request information from you to set up a user account, you must provide us with accurate and complete information and must update the information when it changes. As part of the registration process, you may be asked to choose a user name and password. We may refuse to grant you any particular user name in our sole discretion. You agree to maintain the confidentiality of your access credentials and not share them with any other person. You must notify us immediately if you become aware of any unauthorized use of your access credentials or any other breach of security. Even if you notify us, you are solely responsible for any and all use of your account and access credentials, including for any charges incurred. We are not responsible for any loss or damage resulting from unauthorized use. You may close your account at any time through the "settings" feature or other account management functionality of the applicable Service, or in any event you may contact our customer care department at (877)4-SHOWTIME ((877)474-6984). However, these Terms will continue to apply to your activity while you were registered, including information you provided while your account was active and our records of your activity. These terms also will apply to your subsequent use of the Services not requiring an account registration. </p>

       <p class="legal__body">In connection with an account you register, we and the companies we work with to provide the Services may send you emails regarding the Services from time to time. You agree that we and such companies may send emails relating to the Services to the email address that you provide even if you have opted out of receiving other email from us. </p>

      <h4 class="legal__sub-headline">4. Intellectual Property; License</h4>
      <p class="legal__body">The audio and video materials, photographs, text, graphics, logos, layouts, designs, interfaces, software, data and other content associated with the Services ("Content") are protected by intellectual property and other laws in the U.S. and in other countries. You must comply with all such laws and applicable copyright, trademark or other legal notices or restrictions. You shall not remove or alter any copyright, trademark, or other legal notices marked on the Content. As between you and Provider, Provider will retain all right, title, and interest in and to the Services and the Content. No transfer of ownership to any portion of the Content shall be made as a result of any access you are granted. Except as specifically provided below, we and our licensors reserve all rights to the Services and Content.</p>

      <p class="legal__body">You are only permitted to access and view the Content for personal, non-commercial purposes in accordance with these Terms, and may not build a business or other enterprise utilizing any of the Content, whether for profit or not. Except as provided in Section 4(a) or otherwise expressly authorized by us in writing, you may not either directly or through the use of any software, device, Internet site, web-based service or other means download, stream capture, store in a database, archive or otherwise copy any part of the Services or Content; upload, sell, rent, lease, lend, broadcast, transmit or otherwise disseminate, distribute, display or perform any part of the Services or Content; license or sublicense any part of the Services or Content; or in any way exploit any part of the Services or Content. In addition, except as provided in Section 4(a) or otherwise expressly authorized by us in writing, you are strictly prohibited from modifying Content; creating, distributing or advertising an index of any significant portion of the Content; or otherwise creating derivative works or materials that otherwise are derived from or based in any way on the Content, including mash-ups and similar videos, montages, translations, desktop themes, fonts, icons, wallpaper, greeting cards, and merchandise. This prohibition from creating derivative works is applicable even if you intend to give away the derivative material free of charge.</p>

      <p class="legal__body">Without limiting the foregoing, you may not modify, interfere with, enhance, remove, or otherwise alter in any way any portion of the Provider video player (the "Video Player"); any of the Video Player's underlying technology; or any digital rights management mechanism, device, or other content protection or access control measure incorporated into the Video Player. This restriction includes, without limitation, disabling, modifying, reverse engineering, interfering with or otherwise circumventing the Video Player in any manner that enables users to view Content without: (1) visibly displaying both the Video Player and all surrounding elements (including the graphical user interface, any advertising, copyright notices, and trademarks) of the webpage where the Video Player is located; and (2) having full access to all functionality of the Video Player, including, without limitation, all video quality and display functionality and all interactive, elective or click-through advertising functionality.</p>

      <p class="legal__list-headline">a. Viral Distribution</p>
      <p class="legal__body">We may expressly authorize you to redistribute certain Content on a personal, non-commercial basis. We will identify the Content that you are authorized to redistribute and describe ways you may redistribute it (such as via email, social media posts, blogs, or embedded players, or by producing Mash-Ups). We may revoke this authorization at any time. If you redistribute such Content, you must be able to edit or delete such publicly posted Content and you must edit or delete it promptly upon our request. When expressly authorized by us in writing, you may embed videos using the Video Player, provided you do not embed the Video Player on any website or other location that (1) contains or hosts content that is inappropriate, profane, vulgar, offensive, false, disparaging, defamatory, obscene, illegal, infringing, threatening, sexually explicit, racist, that promotes violence, racial hatred, or terrorism, or that we deem, in our sole discretion, to be otherwise objectionable or (2) links to infringing or unauthorized content, or any content described in above in clause (1). You may not embed the Video Player into any hardware or software application, even for non-commercial purposes. As determined by us in our sole discretion, we reserve the right to prevent embedding to any website or other location that we find inappropriate or otherwise objectionable as determined by us in our sole discretion.</p>

      <p class="legal__body">Some Services may include "Mash-Up Tools" that allow you to manipulate Content or combine User Submissions (as defined in Section 6) with Content to create "Mash-Ups." The following terms apply to your use of Mash-Up Tools, except as specifically provided in other terms accompanying the Mash-Up Tools:  </p>
        <ul class="legal__body__list">
          <li class="legal__body__list-item">You may only use designated Content with the Mash-Up Tools, and we may revoke permission to use the designated Content at any time.</li>
          <li class="legal__body__list-item">You may manipulate or combine the designated Content using the Mash-Up Tools only as authorized and only for personal, non-commercial purposes.</li>
          <li class="legal__body__list-item">As between you and us, we own all compilation rights in the Mash-Ups and may make perpetual and unrestricted use of the Mash-Ups, and you will only retain whatever prior rights you had in your User Submissions.</li>
          <li class="legal__body__list-item">With our permission, other users of the Services may make subsequent Mash-Ups using your Mash-Ups.</li>
          <li class="legal__body__list-item">You must include any required or existing trademark, copyright or other legal notices in the Mash-Ups and you must comply with any other usage or attribution guidelines we provide.</li>
          <li class="legal__body__list-item">If we expressly allow you to do so, you may distribute Mash-Ups under the Viral Distribution guidelines above in Section 4(a) of these Terms.</li>
        </ul>
      <p class="legal__list-headline">b. Commercial Licenses</p>
      <p class="legal__body">You must obtain our written permission for commercial use of the Content or the Services. If you wish to license Content from the Services, please  <a class="legal__body__link" href="/contact">contact us</a>.</p>

      <p class="legal__list-headline">c. Dated Materials</p>
      <p class="legal__body">Content offered through the Services or in links from the Services is dated as of the date originally issued or indicated on the Content and may no longer be accurate.  We assume no obligation to update such Content.</p>

      <h4 class="legal__sub-headline">5. Legal Complaints</h4>
      <p class="legal__list-headline">a. Copyright Claims</p>
      <p class="legal__body">Provider respects intellectual property rights. If you believe that Content on any Service infringes your copyright, a notification of claimed copyright infringement pursuant to the Digital Millennium Copyright Act must be sent to our Designated Agent using the following contact information: </p>
      <p class="legal__body">
        Showtime Networks Inc.<br>
        Attn: Designated Agent<br>
        1633 Broadway<br>
        New York, NY 10019<br><br>
        Email Address: dmcaclaims@showtime.net<br>
        Telephone Number: 212-708-1600<br>
        Facsimile Number: 212-708-1391  <br>
      </p>

      <p class="legal__body caps">DO NOT SEND ANY INQUIRIES UNRELATED TO COPYRIGHT INFRINGEMENT (E.G., REQUESTS FOR TECHNICAL ASSISTANCE OR CUSTOMER SERVICE, REPORTS OF E-MAIL ABUSE) TO THE CONTACT LISTED ABOVE. YOU WILL NOT RECEIVE A RESPONSE IF SENT TO THAT CONTACT.</p>
      <p class="legal__body">Notifications of claimed copyright infringement on the Services must include the following:</p>
      <ul class="legal__body__list">
        <li class="legal__body__list-item">An electronic or physical signature of the owner of the copyright interest that is allegedly infringed, or of a person authorized to act on the copyright owner&rsquo;s behalf;</li>
        <li class="legal__body__list-item">Identification of the copyrighted work (or works) that you claim to have been infringed;</li>
        <li class="legal__body__list-item">Identification of the material that you claim is infringing;</li>
        <li class="legal__body__list-item">A clear description of where the infringing material is located on the Services so that we can locate the material;</li>
        <li class="legal__body__list-item">Your name, address, telephone number, and email address; </li>
        <li class="legal__body__list-item">A statement that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and</li>
        <li class="legal__body__list-item">A statement by you that the information in your notification is accurate and, under penalty of perjury, that you are the copyright owner or are authorized to act on the copyright owner&rsquo;s behalf.</li>
      </ul>

      <p class="legal__list-headline">b. Other Complaints</p>

      <p class="legal__body">If you have a complaint regarding any Content on the Services that is not related to copyright infringement, but concerns Content that is objectionable and/or violates the terms of this Agreement, you may <a class="legal__body__link" href="/contact">contact us</a>.  In your complaint please provide the reason for your complaint, identify the relevant Service and the location of the Content on the Service, the specific type of Content, and the name of the author, if available or applicable.</p>

      <h4 class="legal__sub-headline">6. User Submissions</h4>

      <p class="legal__body">Some of the Services may allow you to submit or transmit to or through the Services audio, video, text, or other materials, including so-called &quot;user generated content&quot; and &quot;feedback&quot; and postings to third-party social media sites (collectively, &quot;User Submissions&quot;).  When you provide User Submissions, you grant to Provider and its affiliates and partners a non-exclusive, worldwide, royalty-free, perpetual, irrevocable, fully sublicensable license to use, reproduce, archive, edit, translate, create derivative works of, make available, distribute, sell, display, perform, transmit, broadcast and in any other way exploit those User Submissions, and any names, voices, likenesses and other identifying information of persons that is part of those User Submissions, in any form, media, software, or technology of any kind now known or developed in the future, including, without limitation, for developing, manufacturing, and marketing products.  You hereby waive any moral rights you may have in your User Submissions. For clarity, we are not required to and will not provide any form of compensation for any use of your User Submissions.</p>

      <p class="legal__body">We respect your ownership of User Submissions.  If you owned a User Submission before providing it to us, you will continue owning it after providing it to us, subject to any rights granted in these Terms and any access granted to others.  Please note that even where a Service provides a deletion capability for User Submissions, and you delete a User Submission from the Service: </p>
        <ul class="legal__body__list">
          <li class="legal__body__list-item">The User Submission may still exist in our backup copies, which are not publicly available.</li>
          <li class="legal__body__list-item">If your User Submission was shared with third parties, those third parties may have retained copies of your User Submissions, and neither we nor our affiliates have any responsibility for any uses of your User Submission that they might make.</li>
          <li class="legal__body__list-item">We retain the license specified above.  Thus, for example, if we or one of our sublicensees obtained your User Submission for use in creating a derivative work before you deleted it, we or our sublicensee would remain free to complete the creation of that derivative work and thereafter exploit that derivative work for all purposes and at all times.</li>
      </ul>

      <p class="legal__body">We may impose limits on the size or number of User Submissions (e.g., limits on storage space or inbound or outbound messages) or otherwise refuse or remove a User Submission with or without cause and without notice to you. However, we have no obligation to monitor User Submissions, and you agree that neither we nor our affiliates will be liable for (1) User Submissions; (2) any failure to store, receive or deliver User Submissions; or (3) any loss or damage resulting from User Submissions. </p>

       <p class="legal__body">We do not guarantee that User Submissions will be private, even if the User Submission is in a password-protected area. Accordingly, you should not provide User Submissions that you want protected from others.</p>

        <p class="legal__body">You bear all responsibility for your User Submissions. You represent and warrant that you have all rights necessary to grant to Provider the license above and that your User Submissions do not violate Section 12.</p>

        <h4 class="legal__sub-headline">7. Third-Party Content, Products and Services</h4>
        <p class="legal__body">We may provide third party content (including advertisements), products or services or link to third party websites or other services on the Services. We do not necessarily endorse or evaluate third party content, products and services; we do not assume responsibility for third parties' actions or omissions; and we have no liability whatsoever for goods and services you may obtain from or through other services, even if you were directed or linked to such a service through our Service. You should review third parties' terms of use and privacy policies before you use their services. In certain instances, you may be able to connect and/or link your account to certain third party social media sites ("Social Media Sites"), including, without limitation, Facebook and Twitter. BY CONNECTING OR LINKING YOUR ACCOUNT TO ANY SOCIAL MEDIA SITE, YOU ACKNOWLEDGE AND AGREE THAT YOU ARE CONSENTING TO THE CONTINUOUS RELEASE OF INFORMATION ABOUT YOU TO OTHERS, INCLUDING TO THE SOCIAL MEDIA SITE (IN ACCORDANCE WITH YOUR PRIVACY SETTINGS ON SUCH SOCIAL MEDIA SITE). IF YOU DO NOT WANT INFORMATION ABOUT YOU TO BE SHARED IN THIS MANNER, DO NOT CONNECT OR LINK YOUR ACCOUNT TO ANY SOCIAL MEDIA SITE. </p>
 
        <h4 class="legal__sub-headline">8. Streaming Service Subscriptions and Billing</h4>
        <p class="legal__body">This Section 8 contains additional provisions that apply if you subscribe to the Streaming Service.</p>

        <p class="legal__body">8.1 Streaming Service Account Information. You can access and edit specific details regarding your subscription to the Streaming Service (including information concerning your credit card or other available payment method ("Payment Method") if you purchase your subscription from Provider) on the Streaming Service's website under "Settings."</p>

        <p class="legal__body">8.2 Device Requirements. To see if the Streaming Service is available for your device see our Help Center.</p>

        <p class="legal__body">8.3 Payment and Pricing. By placing an order for the Streaming Service through an authorized third-party distributor or Provider (each a "Distributor") and providing a Payment Method to that Distributor, you are agreeing to pay a subscription fee and any applicable taxes and service fees ("Fees") for the Streaming Service on the payment cycle designated by the Distributor. The Fees will be charged to your Payment Method at the beginning of your subscription (or, as described in Section 8.8, at the end of your Trial Period, where applicable), and thereafter on a recurring basis in accordance with your designated payment cycle, unless you cancel your subscription or your account or the Streaming Service is suspended or terminated pursuant to these Terms. Billing policies are set by Distributors. If you purchase a monthly subscription to the Streaming Service from Provider and your subscription begins after the 28th of a month, then in any subsequent month in which that day does not occur, we will charge your Payment Method on approximately the last day of such month. For example, if you started your subscription on January 31st, your next payment date will be approximately February 28th. If you do not purchase your subscription to the Streaming Service through Provider, you should confirm your Distributor's billing policies before subscribing to the Streaming Service. The Fees charged to your Payment Method may vary from time to time due to changes in your subscription plan or applicable taxes, and you authorize your Distributor to charge your Payment Method for these amounts. Each Distributor reserves the right to change the price for a subscription to the Streaming Service and will be responsible for communicating any price changes to you. If you do not wish to accept a price change, you may cancel your Streaming Service subscription as described in Section 8.5. YOU ARE RESPONSIBLE FOR ALL INTERNET ACCESS CHARGES. PLEASE CHECK WITH YOUR INTERNET PROVIDER FOR INFORMATION ON POSSIBLE INTERNET DATA USAGE CHARGES.</p>

        <p class="legal__body">8.4 No Refunds. ALL FEES ARE NON-REFUNDABLE. As described further in Section 8.5, even if you cancel the Streaming Service during a paid subscription period, you will not receive a refund for any portion of the Fees for the remainder of that subscription period. A Distributor may provide a credit, discount, or other consideration ("Credits") to certain subscribers in certain circumstances. The amount and form of such Credits, and the decision to provide them, are at the Distributor's sole discretion. The provision of Credits in one instance does not entitle you to Credits in the future for similar instances, nor does it obligate Provider or any other Distributor to provide Credits in the future, under any circumstance.</p>

        <p class="legal__body">8.5 Cancellation. If you purchased your subscription to the Streaming Service from Provider, you can cancel your subscription at any time by going to the "Settings" feature of the Streaming Service's website or by contacting us at showtime.com/help. If you purchased your subscription to the Streaming Service from another Distributor, you can cancel your subscription to the Streaming Service at any time through such Distributor's platform. With respect to all Distributors, if you cancel your subscription, the cancellation will go into effect at the end of your then-current paid subscription period. You will have continued access to the Streaming Service for the remainder of your paid subscription period, but YOU WILL NOT RECEIVE A REFUND OF ANY FEES PAID. You must cancel your subscription before it renews for the next period to avoid paying the Fees for the next period. You acknowledge and agree that cancellation of your subscription is your sole recourse if you have any dissatisfaction, issue or concern related to the Streaming Service, its Content or features, Fees, applicable taxes, or billing methods; the selection of Content available to you through the Streaming Service; these Terms, including the Provider Privacy Policy, or any changes thereto; your Distributor's billing or other policies; or any other the Streaming Service policies or practices.</p>

        <p class="legal__body">8.6 Updating Payment Method; Unpaid Amounts. You may update your Payment Method for the Streaming Service through your account with your Distributor. If your Distributor is Provider, you may update your Payment Method for the Streaming Service on the Streaming Service's website under "Settings." If you fail to pay any Fees when due, as a result of expiration of your Payment Method, invalid account details, insufficient funds, or otherwise, (1) you will remain liable for all such amounts, as well as any costs that your Distributor incurs in collecting any amounts you fail to pay in connection with the Streaming Service, including attorney and collections fees; (2) you authorize your Distributor to continue charging your Payment Method, as your Payment Method information may be updated as described above in this Section 8.6; and (3) your Distributor may suspend or terminate your subscription. Changing your Payment Method information may result in changes to your billing cycle.</p>
        
        <p class="legal__body">8.7 Promo Codes. From time to time, promotional codes may be available, including those provided as part of a third party promotion. Promotional codes may be redeemed as described in the specifics of the promotion. Promotional codes can only be used once, cannot be redeemed for cash, and may be combined with other offers, subject to certain restrictions as determined by Provider in its sole discretion. If you received a promotional code through an offer by a third party, additional conditions may apply.</p>

        <p class="legal__body">8.8. Trial Period. The Streaming Service may be offered to certain users on a free trial subscription basis for a limited time ("Trial Period"). Distributors are under no obligation to provide a Trial Period, and Trial Periods may not be available at all times. Each Distributor, as the case may be, reserves the right, in its absolute discretion, to determine your eligibility for a Trial Period. The specific terms of the Trial Period will be stated in the marketing material describing the particular Trial Period. Your subscription starts at the beginning of the Trial Period. Unless otherwise specified, (1) you may only have one Trial Period before you must begin paying for the Streaming Service, and if you exceed this limit, your Distributor may charge your Payment Method for any period after the first Trial Period, or suspend your use of the Streaming Service, in its sole discretion; (2) you must provide valid Payment Method information to use the Streaming Service during the Trial Period (although you will not be charged in connection with the Trial Period); (3) if you do not cancel the Streaming Service by the end of your Trial Period, you authorize your Distributor to automatically charge your Payment Method for the subscription period that follows immediately after the end of your Trial Period; (4) YOUR DISTRIBUTOR MAY NOT SEND YOU NOTICE THAT YOUR TRIAL PERIOD HAS ENDED OR THAT YOUR OBLIGATION TO PAY FOR YOUR SUBSCRIPTION HAS BEGUN; and (5) IF YOU WISH TO AVOID CHARGES TO YOUR PAYMENT METHOD, YOU MUST CANCEL THE SUBSCRIPTION PRIOR TO THE END OF YOUR TRIAL PERIOD.</p>
        
        
        <p class="legal__body">8.9 Gift Cards. Physical and digital gift cards may be available for subscriptions to the Streaming Service ("Gift Cards") in the United States. Internet access is required to redeem any Gift Card. Gift Cards can be redeemed at www.showtime.com/redeem. Your purchase and use of a Gift Card is governed by the Gift Card terms found <a class="legal__body__link" href="https://www.showtime.com/giftterms">here</a>.</p>

        <p class="legal__body">8.10. Updates and Testing. Provider reserves the right to update and change the Streaming Service, including its features and the selection of Content available through the Streaming Service, at any time. In addition, Provider reserves the right to test various aspects of the Streaming Service. Provider reserve the right to, and by using our Services you agree that we may, include you in or exclude you from these tests without notice.</p>

        <h4 class="legal__sub-headline">9. Showtime Anytime Accounts</h4>
        <p class="legal__body">This Section 9 contains additional provisions that apply to Showtime Anytime.</p>
        <p class="legal__body"> 9.1. Requirements for Registration and Use. To be a registered user of Showtime Anytime, you must meet the following criteria: (1) you must reside in the U.S.; (2) you must be one of up to five members of a household with an account in good standing with your participating provider; and (3) your household must subscribe to SHOWTIME through your participating provider. To register, you will be required to enter the credentials that you have established with your participating provider for accessing Showtime Anytime and provide certain additional registration details. The primary account holder established with your participating provider must register for the Service before any sub-account holder may do so. No more than three members of a household are permitted stream content at any one time.</p>

        <p class="legal__body">9.2 Access by Children. Showtime Anytime contains certain mature content that may not be appropriate for children. If the primary account holder chooses to allow any linked sub-account holder to access adult or mature content available on Showtime Anytime, the primary account holder acknowledges and agrees that such sub-account holder may be exposed to adult language as well as visual images and audio depicting nudity, sexual activity and violence. The primary account holder may establish certain "Parental Controls" through the relevant participating provider or, in certain instances, through Showtime Anytime. We will recognize the maximum movie and television ratings set by the primary account holder for each sub-account that is linked to the primary account holder.</p>

        <p class="legal__body">9.3. Termination of Your Registration. You may terminate your registration for Showtime Anytime at any time by (1) if you are a SHOWTIME subscriber through your participating provider at the time you wish to terminate your registration (a "Current SHO Subscriber"), returning to the "Settings" page of Showtime Anytime and following the instructions for termination; or (2) if you are not a Current SHO Subscriber at the time you wish to terminate your registration, by sending an email requesting termination to contact@showtime.net. If a primary account holder chooses to terminate a primary account registration, the registrations of all sub-accounts linked to the primary account holder will be terminated at the same time. We may terminate your registration at any time, with or without notice and with or without cause. </p>

        <h4 class="legal__sub-headline">10. Other Fee-Based Offerings</h4>
        <p class="legal__body">If you accept fee-based Services other than the Streaming Service or Showtime Anytime, you agree to the additional terms governing all such purchases as provided to you or posted on the Services to which they apply, including all requirements to pay applicable fees and taxes. Except as otherwise provided in such additional terms, the provisions of this Section 10 apply to such fee-based Services.</p>

        <p class="legal__body">Unless otherwise stated, all fees and charges are non-refundable, including for unused portions of cancelled subscriptions. We do not provide price protection or refunds in the event of a price drop or promotional offering.</p>
        
        <p class="legal__body">Provider reserves the right to change the pricing of all Services at any time. In the event of a price change, Provider will post the new pricing on the relevant Service and attempt to notify you by sending an email to the address you have registered. Billing for all mobile subscription services will be governed by the Mobile Features section of these Terms (Section 11) unless the terms of the subscription say otherwise.</p>

        <p class="legal__body">We may offer trial subscriptions to paid Services for free or at special discounted prices. Unless otherwise stated, these trial subscriptions will automatically become paying subscriptions at the current subscription rate if you do not cancel before the end of the trial period.</p>

        <p class="legal__body">The Services may offer various products for sale ("Products"). You are responsible for any taxes imposed on the sale or use of Products, and applicable taxes will be added to the amount charged for Products purchased on through the Services. </p>

        <h4 class="legal__sub-headline">11. Mobile Features</h4>
        <p class="legal__body">This Section 11 contains additional provisions that apply to Services designed for wireless devices (&quot;Mobile Features&quot;).</p>

        <p class="legal__body">Your wireless provider may charge for use of Mobile Features, including fees for receipt of text messages or data transmission. In order to receive Mobile Features, your wireless provider may require you to subscribe to additional services, which may require additional fees. These fees are not charged by us, and you should contact your wireless provider before you sign up for Mobile Features to determine what fees, if any, will be charged. In addition, you agree that we may arrange for Mobile Features billing through your wireless provider and that your wireless provider may invoice you for the applicable fees or deduct them from your pre-paid balance.</p>

        <p class="legal__body">You may not transfer or copy any Content from the wireless device on which you originally received Content to any other device, including, without limitation, any computer or another wireless device.</p>

        <p class="legal__body">To cancel a Mobile Feature that involves a subscription fee, you must follow the instructions included in the terms and conditions applicable to that Mobile Feature; otherwise, you will continue to incur subscription charges. If you stop a subscription-based Mobile Feature in the middle of a billing cycle, you will not receive a refund for that billing cycle.</p>
        <h4 class="legal__sub-headline">12. Acceptable Use</h4>
        <p class="legal__body">Without limiting any other provision in these Terms, you agree not to do the following, or assist others to do the following: </p>
          <ul class="legal__body__list">
            <li class="legal__body__list-item">Access the Services using any interface other than ours, including by making any automated use of the Services such as using scripts to interact with the Services.</li>

            <li class="legal__body__list-item">Maintain any link to the Services that we ask you to remove, in our sole discretion.</li>

            <li class="legal__body__list-item">Frame the Services or Content, make the Services or Content available via in-line or "deep" links, otherwise display the Services or Content in connection with an unauthorized logo or mark, or do anything that could falsely suggest a relationship between the Provider or its affiliates and any third party or potentially deprive us of revenue (including, without limitation, revenue from advertising, branding, or promotional activities).</li>

            <li class="legal__body__list-item">Threaten, defame, stalk, abuse, or harass other persons or engage in illegal activities, or encourage conduct that would constitute a criminal offense or give rise to civil liability.</li>

            <li class="legal__body__list-item">Transmit any material that is inappropriate, profane, vulgar, offensive, false, disparaging, defamatory, obscene, illegal, sexually explicit, racist, that promotes violence, racial hatred, or terrorism, or that we deem, in our sole discretion, to be otherwise objectionable.</li>

            <li class="legal__body__list-item">Violate any person's or entity's legal rights (including, without limitation, intellectual property, privacy, and publicity rights), transmit material that violates or circumvents such rights, or remove or alter intellectual property or other legal notices.</li>

            <li class="legal__body__list-item">Transmit files that contain viruses, spyware, adware, or other harmful code.</li>
            <li class="legal__body__list-item">Advertise or promote goods or services without our permission (including, without limitation, by sending unsolicited email through a Service or linking to a Service).</li>
 
            <li class="legal__body__list-item">Interfere with others using the Services or otherwise disrupt the Services.</li>
            <li class="legal__body__list-item">Disassemble, decompile or otherwise reverse engineer any software or other technology included in the Content or used to provide the Services.</li>
            <li class="legal__body__list-item">Transmit, collect, or access personally identifiable information about other users without the consent of those users and Provider.</li>
            <li class="legal__body__list-item">Engage in unauthorized spidering, "scraping," data mining or harvesting of Content, or use any other unauthorized automated means to gather data from or about the Services.</li>
            <li class="legal__body__list-item">Impersonate any person or entity or otherwise misrepresent your affiliation or the origin of materials you transmit.</li>
            <li class="legal__body__list-item">Remove, avoid, interfere with, or otherwise circumvent any access control measures for the Services or Content, including password-protected areas and geo-filtering mechanisms, or any digital rights management measures used in connection with Content.</li>
            <li class="legal__body__list-item">Access any portion of the Services that we have not authorized you to access (including password-protected areas), link to password-protected areas, attempt to access or use another user's account or information, or allow anyone else to use your account or access credentials.</li>
            <li class="legal__body__list-item">Manipulate the entry or registration process for contests, sweepstakes, surveys, opinion polls or other features of the Services.</li>
          </ul>

        <p class="legal__body">If we believe you have violated this Section 12, we may immediately terminate your access to the Services, and take any other actions or seek any remedies permitted by law.</p>

        <h4 class="legal__sub-headline">13. Access to Services and Accounts</h4>

        <p class="legal__body">To access the Services, your device must be connected to the Internet, and you are solely responsible for the cost and maintenance of your Internet connection. You are also responsible for ensuring that you have the hardware and software platforms that are necessary to access the Services.</p>

        <p class="legal__body">The quality of the display of the Content available through the Services may vary from device to device, and may be affected by a variety of factors, including your location and the speed of your Internet connection. The time it takes to begin watching Content will also vary based on a number of factors, including your location, available bandwidth at the time and the configuration of your device. Provider makes no representations or warranties about the quality of your watching experience on your device.</p>

        <p class="legal__body">Certain Content transmitted on the SHOWTIME television service may not be available through the Services. Provider will not be liable to you for any blackouts, location-based limitations, device-based limitations, Content-viewing windows, availability of Content, or other restrictions or limitations in connection with the Services or the Content.</p>

        <p class="legal__body">We may take any of the following actions in our sole discretion at any time, and without giving you prior notice: </p>
          <ul class="legal__body__list">
            <li class="legal__body__list-item">Change or discontinue the Services.</li>
            <li class="legal__body__list-item">Change how we offer and operate Services (e.g., to begin charging a fee to access features or Content that we previously made available without charge).</li>
            <li class="legal__body__list-item">Remove Content from the Services.</li>
            <li class="legal__body__list-item">Restrict, suspend or terminate your access to one or more Services or features thereof. 
            <li class="legal__body__list-item">Deactivate your accounts and delete all related information and files in your accounts.</li>
          </ul>

        <p class="legal__body">We will not be liable to you or any third party for taking any of these actions and we will not be limited to the remedies above if you violate these Terms. If Provider terminates your access to any of the Services, you must immediately stop using such Service. In the case of the Streaming Service, any entitlement you may have to a refund will be determined by your Distributor. If Provider terminates your access to the Streaming Service or another paid Service because you breached these Terms, you will not be entitled to any refund.</p>

        <p class="legal__body">Provider reserves the right to test various aspects of the Services. Provider reserves the right to, and by using our Services you agree that we may, include you in or exclude you from these tests without notice.</p>

        <h4 class="legal__sub-headline">14. Unsolicited Submissions  </h4>
        <p class="legal__body">Provider does not accept unsolicited submissions, including scripts, story lines, articles, fan fiction, characters, drawings, suggestions, ideas or concepts. It is Provider's policy to delete any such submission without reading it. Any similarity between an unsolicited submission and any elements in any Provider creative work would be purely coincidental.</p>
        
        <h4 class="legal__sub-headline">15. Indemnification</h4>

        <p class="legal__body">You will defend, indemnify and hold harmless Provider, its affiliates, and their respective directors, officers, employees, shareholders, vendors, partners, contractors, agents, licensors or other representatives and all of their successors and assigns (collectively, the "Provider Parties") with respect to all third party claims, costs (including attorney's fees and costs), damages, liabilities, and expenses or obligations of any kind, arising out of or in connection with your use or misuse of the Services (including, without limitation use of your account, whether or not authorized by you, and claims arising from User Submissions). Provider retains the right to assume the exclusive defense and control of any claim subject to indemnification, and in such cases you agree to cooperate with us to defend such claim. You may not settle any claim covered by this Section 15 without Provider's prior written approval.</p>

        <h4 class="legal__sub-headline">16. Disclaimers; Limitation of Liability</h4>

        <p class="legal__body">THE PROVIDER PARTIES DO NOT WARRANT: (1) THAT THE SERVICES, ANY OF THE SERVICES' FUNCTIONS OR ANY CONTENT WILL BE UNINTERRUPTED OR FREE OF ERRORS OR OMISSIONS; (2) THAT DEFECTS WILL BE CORRECTED; (3) THAT THE SERVICES OR THE SERVERS HOSTING THEM ARE FREE OF VIRUSES OR OTHER HARMFUL CODE; OR (4) THAT THE SERVICES OR INFORMATION AVAILABLE THROUGH THE SERVICES WILL CONTINUE TO BE AVAILABLE. THE PROVIDER PARTIES SHALL HAVE NO LIABILITY FOR ANY SUCH ISSUES. THE PROVIDER PARTIES DISCLAIM ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, NONINFRINGEMENT, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND AS TO QUALITY, AVAILABILITY AND SUBJECT MATTER OF CONTENT. THE SERVICES, INCLUDING ALL CONTENT AND FUNCTIONS MADE AVAILABLE ON OR ACCESSED THROUGH OR SENT FROM THE SERVICES, ARE PROVIDED "AS IS," "AS AVAILABLE," "WITH ALL FAULTS" AND "AT YOUR OWN RISK." NO ADVICE OR INFORMATION OBTAINED BY YOU FROM US, OR FROM OR THROUGH THE SITE, SHALL CREATE ANY WARRANTY.</p>

        <p class="legal__body">YOUR ACCESS TO AND USE OF THE SERVICES (INCLUDING THEIR FUNCTIONS AND CONTENT) IS AT YOUR RISK. IF YOU ARE DISSATISFIED WITH THE SERVICES, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE ACCESSING AND USING THE SERVICES.</p>

        <p class="legal__body">THE PROVIDER PARTIES WILL NOT BE LIABLE FOR ANY FAILURE OR DELAY IN THEIR PERFORMANCE DUE TO ANY CAUSE BEYOND THEIR REASONABLE CONTROL, INCLUDING ACTS OF WAR, ACTS OF GOD, ACTS OF THIRD PARTY SERVICE PROVIDERS, EARTHQUAKE, FLOOD, EMBARGO, RIOT, SABOTAGE, LABOR SHORTAGE OR DISPUTE, GOVERNMENTAL ACT, POWER FAILURE OR FAILURE OF THE INTERNET OR COMPUTER EQUIPMENT.</p>

        <p class="legal__body">YOU ACKNOWLEDGE AND AGREE THAT IF YOU INCUR ANY DAMAGES THAT ARISE OUT OF THE PROVIDER PARTIES' ACTS OR OMISSIONS, THE DAMAGES, IF ANY, ARE NOT IRREPARABLE AND ARE NOT SUFFICIENT TO ENTITLE YOU TO AN INJUNCTION OR OTHER EQUITABLE RELIEF RESTRICTING OPERATION OF THE SERVICES OR ANY OTHER SERVICE, PROPERTY, PRODUCT, PROGRAM, TELEVISION SHOW, MOTION PICTURE, OR OTHER CONTENT OWNED OR CONTROLLED BY THE PROVIDER PARTIES.</p>

        <p class="legal__body">SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO SOME OF THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>

        <h4 class="legal__sub-headline">17. Governing Law, Venue, and Jurisdiction </h4>
        <p class="legal__body">These Terms and all claims arising from or related to your use of the Services will be governed by and construed in accordance with the laws of the State of New York, except New York's conflict of law rules. These Terms will not be governed by the United Nations Convention on Contracts for the International Sale of Goods, if applicable.</p>

        <p class="legal__body">With respect to any disputes or claims not subject to arbitration or small claims court (as set forth in Section 1 above), you agree to exclusive jurisdiction in the state and federal courts in New York, New York.</p>

        <p class="legal__body">Regardless of any statute or law to the contrary, you must file any claim or action related to use of the Services or these Terms within one year after such claim or action accrued. Otherwise, you will waive the claim or action.</p>

        <h4 class="legal__sub-headline">18. Miscellaneous </h4>
        <p class="legal__body">We may be required by state or federal law to notify you of certain events. You hereby acknowledge and agree that such notices will be effective upon our posting them in the relevant Service or delivering them to you via email. You may update your email address by visiting the Services where you have provided contact information. If you do not provide us with accurate information, we will not be responsible for failure to notify you. Our failure to exercise or enforce any right or provision in these Terms will not constitute a waiver of such right or provision. These Terms, including all additional terms, conditions, and policies on the Services, constitute the entire agreement between you and us and supersede all prior agreements with respect to the subject matter hereof. Nothing in these Terms affects any non-waivable statutory rights that apply to you. If any part of these Terms is determined to be invalid or unenforceable under applicable law, that provision will be removed, and the remainder of the Terms will continue to be valid and enforceable.</p>

        <p class="legal__body">You authorize us to provide information concerning you and your activities to comply with applicable laws or respond to court order, subpoenas, or other lawful requests, or if we believe doing so would protect your safety or that of another person or protect the security of the Services, or as otherwise described in the  <a class="legal__body__link" href="https://www.viacomcbsprivacy.com/policy">Privacy Policy</a>, subject to your right to make certain choices about our use of your personal information as described in the Privacy Policy.
        </p>

        <p class="legal__body">If you do not agree to these Terms, you should immediately stop using the Services. If you want to delete your account on a Service, you may be able to do so through the "settings" feature or other account management functionality of the applicable Service, or in any event you may contact our customer care department at (877)4-SHOWTIME ((877)474-6984). If you are a Streaming Service subscriber, you must first cancel your subscription before you will be able to delete your account. Any User Submissions you made while using the Services will continue to be governed by Section 6 of these Terms.</p>

        <p class="legal__body">Sections 1, 5 and 11-17 of these Terms will survive any termination of your access to the Services, whether we terminate your access or you voluntarily discontinue your use. </p>
        <p class="legal__body">Please contact us with any questions regarding these Terms through the contact or help feature of the relevant Service or by calling our customer care department at (877)4-SHOWTIME ((877)474-6984).</p>
      </section>

      {{#popularSeriesGroup}}
        {{> series/partials/_series_slider}}
      {{/popularSeriesGroup}}
    {{/page}}
  {{/content}}
{{/ layouts/default}}
