{{!-- 
  # network feed terms
--}}

{{< layouts/default }}
  {{$classnames}}has-nav-solid has-nav-exposed network-feed--terms{{/classnames}}
  
  {{$meta}}
	  <title>Showtime Marketing Feed</title>
    <meta property="og:title" content="Showtime Marketing Feed" />
    <meta name="description" content="Authorized developers may use this feed from Showtime Networks Inc. to access official schedule, metadata and promotional assets" />
    <meta property="og:description" content="Authorized developers may use this feed from Showtime Networks Inc. to access official schedule, metadata and promotional assets" />
		<meta name="page-tracking" content="sho:utility:network feed:terms" />
  {{/meta}}
  
	<h4 class="legal__sub-headline">

  {{$content}}
    <section class="section section--large legal">
			<h2 class="legal__headline">NETWORK FEED AGREEMENT</h2>
			<p class="legal__body">IMPORTANT! PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY BEFORE USING SHOWTIME NETWORK INC.'S FEEDS CONTAINING PROGRAM-RELATED MATERIALS, SUCH AS SCHEDULES, METADATA, MARKETING AND PROMOTIONAL MATERIALS, CURRENTLY LOCATED AT <a class="legal__body__link" href="/network-feed/home">WWW.SHO.COM/NETWORK-FEED/HOME</a> (THE "FEEDS") AS IT AFFECTS YOUR LEGAL RIGHTS AND OBLIGATIONS.</p>
			<p class="legal__body">THESE TERMS & CONDITIONS ("TERMS") GOVERN YOUR USE OF THE FEEDS. You agree to these Terms by accessing the Feeds, registering for the Feeds, or by accepting or downloading any information or content from the Feeds. If you DO NOT AGREE to be bound by all of these Terms, DO NOT USE the Feeds.</p>
			<p class="legal__body">The Feeds are owned and operated by Showtime Networks Inc. ("Company"). The Feeds are for access and use only by employees of Company or its related companies, and members of the press and other individuals who are pre-approved by Company through Company's authorization process (each individual, an "Authorized User"). The Feeds are for viewing solely in the United States, its territories and possessions. The Feeds may not be viewed or accessed by anyone other than Authorized Users.</p>
			<h4 class="legal__sub-headline">I. OWNERSHIP OF MATERIALS</h4>
			<p class="legal__body">These Feeds and all of the content they contain, or may in the future contain, including, without limitation, guides, photographs, images, video clips, synopses, cast lists, schedules, advertising copy, electronic press kits, as well as the trademarks, logos, domain names, trade names, service marks, trade identities and any and all copyrightable materials (including source and object code) and any other form of intellectual property (collectively, "Material" or "Materials") are owned by or licensed to Company or other authorized third parties and are protectable as intellectual property or otherwise. Except as expressly set forth in these Terms, no rights (either by implication, estoppel or otherwise) are granted to you and you may not use the Materials except as expressly set forth in these Terms. UNAUTHORIZED COPYING, REPRODUCTION, REPUBLISHING, ALTERATION, EDITING, UPLOADING, DOWNLOADING, POSTING, TRANSMITTING OR DUPLICATING OF ANY OF THE MATERIALS IS PROHIBITED.</p>
			<h4 class="legal__sub-headline">II. PASSWORD AND ACCESS RIGHTS</h4>
			<p class="legal__body">As an Authorized User, you are responsible for all activities that occur under your account, and agree that you will not sell, transfer or assign your access rights. You also understand that Company and its agents will be entitled to monitor your account. You understand that you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer so that others may not access the Feeds using your user name or password in whole or in part. You will notify Company immediately if you believe your password has been compromised or the security of your account is threatened in any way.</p>
			<p class="legal__body">By submitting your information to become an Authorized User you are representing and warranting to Company that: (a) you are using your actual identity and the information you provide to Company is true, complete, correct and current, and that you will maintain and update that information as circumstances require; (b) you have the capacity to enter into these Terms (i.e., you are of sufficient legal age and mental capacity); and (c) you are otherwise entitled to be legally bound in contract. Company reserves the right to terminate or suspend your access, or deny or refuse access to the Feeds to any person at any time. If you cease to be an Authorized User for any reason, or upon Company's demand at any time, you must destroy any Materials in your possession, whether in electronic or printed format, unless instructed otherwise by Company in writing.</p>
			<h4 class="legal__sub-headline">III. GENERAL RESTRICTIONS ON USE</h4>
			<p class="legal__body">In connection with your use of the Feeds and Materials, you agree not to: (a) transmit or otherwise make available any junk mail, spam, chain letters, or pyramid schemes; (b) violate any applicable local, state, federal or international law, rule or regulation; (c) transmit any code, file or program designed to interrupt, corrupt, destroy or limit the functionality of any computer software or hardware, telecommunications equipment or other technology used in connection with the Feeds (including, without limitation, any virus, worm, trap door, back door, Trojan horse or other technology that would allow unauthorized access to the Feeds or any Authorized User's software, hardware, computing environment or network); or (d) use the Feeds or Materials for any purpose other than for the uses expressly permitted in these Terms.</p>
			<p class="legal__body">You understand and agree that Company may add, revise, discontinue, delete or suspend any content on the Feeds at any time, without notice and without liability.</p>
			<h4 class="legal__sub-headline">IV. LICENSE/ SPECIFIC RESTRICTIONS ON USE</h4>
			<p class="legal__body">As part of the Feeds' function, Company is making available to Authorized Users certain Materials for viewing, and downloading, using and distributing, and Company hereby grants Authorized Users a limited, personal, non-transferable, non-assignable, non-exclusive, revocable license to access and view and download, use and distribute the Materials solely subject to the terms and conditions set forth in this Section and elsewhere in these Terms.</p>
			<p class="legal__body">Period and Territory for Use of Materials: The license granted herein to download and/or otherwise use and distribute any element of the Materials (i) applies solely in the United States, its territories and possessions, and in Bermuda and (ii) commences on the date such element is disseminated on the Feeds by Company and automatically terminates on the end date associated with such element as indicated in the metadata for such element.</p>
			<p class="legal__body">Permitted Uses of Materials: The license granted herein to download and distribute the Materials is solely for use in connection with news and editorial reporting about Company or promotion of Company's programming services or one of its programs on entertainment listings or guides on websites or software applications, in all cases, owned and managed by you, expressly excluding third party websites or software applications (the "Permitted Uses"). The Permitted Uses do not include use of the Materials in advertisements, or in any manner that suggests, implies or constitutes an endorsement by any individual or organization in or referred to in the Materials or by Company of any third-party product or service.</p>
			<p class="legal__body">Except as authorized by Company, you agree that you will not (1) sublicense, assign or otherwise transfer the license set forth herein (or purport to do any of the foregoing); (2) use the Materials for any purpose other than the Permitted Uses; (3) attempt to decompile, reverse engineer or disassemble any software contained on the Feeds or in the Materials; (4) remove any copyright, trademark or other proprietary notations from the Materials or in any other way alter, modify or edit any given element of the Materials; (5) transfer the Materials to a person or entity for purposes unrelated to your Permitted Uses of the Materials; (6) "mirror" the Feeds on any other server; (7) sell or lease any Materials on a stand-alone basis; or (8) archive the Materials for the purpose of using or providing access to the Materials in violation of these Terms. In addition, you agree that you will be responsible and liable to Company for the actions of any third party to whom you provide access to the Materials. Your misuse of the Materials is strictly prohibited. The rights granted in these Terms will automatically terminate if you violate any of these restrictions, and may be terminated by Company at any time, in its sole discretion.</p>
			<h4 class="legal__sub-headline">V. INFORMATION SUBMITTED BY YOU</h4>
			<p class="legal__body">The Feeds do not accept any materials of any kind from Authorized Users or any other parties (other than the information you provide to become an Authorized User or any questions you may submit in accordance with Section XI below). Therefore, do not attempt to make any such submissions through the Feeds.</p>
			<h4 class="legal__sub-headline">VI. DISCLAIMERS/ LIMITATIONS ON LIABILITY</h4>
			<p class="legal__body">EXCEPT AS EXPRESSLY SET FORTH IN THESE TERMS, THESE FEEDS AND ALL MATERIALS CONTAINED WITHIN THEM ARE DISTRIBUTED "AS IS," "AS AVAILABLE" AND "WITH ALL FAULTS" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE OR IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OF ANY THIRD-PARTY RIGHT OR FITNESS FOR A PARTICULAR PURPOSE OR THOSE ARISING BY STATUTE OR OTHERWISE IN LAW OR FROM A COURSE OF DEALING OR USAGE OF TRADE.</p>
			<p class="legal__body">YOU AGREE THAT COMPANY MAKES NO WARRANTY THAT THE FEEDS WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS, OR THAT THE FEEDS WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR OR VIRUS FREE.</p>
			<p class="legal__body">THE FEEDS MAY BE TEMPORARILY UNAVAILABLE DUE TO MAINTENANCE OR MALFUNCTION OF COMPUTER EQUIPMENT. COMPANY IS NOT RESPONSIBLE FOR ANY RESULTING DAMAGE TO ANY AUTHORIZED USER'S COMPUTER FROM ANY SECURITY BREACH, OR FROM ANY VIRUS, BUGS, TAMPERING, UNAUTHORIZED INTERVENTION, FRAUD, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER LINE FAILURE OR ANY OTHER TECHNICAL OR OTHER MALFUNCTION.</p>
			<p class="legal__body">COMPANY LIMITS ITS LIABILITY IN CONNECTION WITH YOUR USE OF THE FEEDS AS SET FORTH BELOW:</p>
			<p class="legal__body">EXCEPT IN JURISDICTIONS IN WHICH LIABILITY FOR INJURY OR DEATH DUE TO NEGLIGENCE OR ANY OTHER LIABILITY WHICH CANNOT BE EXCLUDED OR LIMITED BY LAW (FOR WHICH NO LIMIT APPLIES): YOU AGREE THAT COMPANY AND ITS AFFILIATES, AS APPLICABLE, ARE NOT LIABLE TO YOU FOR ANY LOSS, DAMAGES OR LOSS OF GOODWILL OF ANY KIND, WHETHER BASED IN TORT, CONTRACT, STRICT LIABILITY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY DIRECT, SPECIAL, INDIRECT, INCIDENTAL, EXEMPLARY, CONSEQUENTIAL OR PUNITIVE DAMAGES RESULTING IN ANY WAY FROM OR IN CONNECTION WITH THESE FEEDS OR THE MATERIALS, ANY ACTION TAKEN IN CONNECTION WITH AN INVESTIGATION BY COMPANY OR LAW ENFORCEMENT AUTHORITIES REGARDING YOUR USE OF THE FEEDS OR THE MATERIALS, OR ANY ERRORS OR OMISSIONS IN THE TECHNICAL OPERATION OR THE MATERIALS OF THE FEEDS, EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, WHETHER CAUSED IN WHOLE OR IN PART BY NEGLIGENCE, ACTS OF GOD, TELECOMMUNICATIONS FAILURE, THEFT OR DESTRUCTION OF, OR UNAUTHORIZED ACCESS TO, THESE FEEDS OR THEIR RELATED INFORMATION OR PROGRAMS; AND NOTWITHSTANDING ANY OTHER PROVISION IN THESE TERMS, IN NO EVENT AND UNDER NO CIRCUMSTANCES WILL COMPANY OR ITS AFFILIATES BE LIABLE TO YOU FOR ANY REASON OR ANY CAUSE OF ACTION RELATED TO THE FEEDS WHATSOEVER IN AN AMOUNT GREATER THAN FIFTY DOLLARS ($50).</p>
			<h4 class="legal__sub-headline">VII. INDEMNIFICATION</h4>
			<p class="legal__body">By agreeing to these Terms, you agree to indemnify, defend and hold harmless Company and its related entities from and against any claims, alleged claims, demands, causes of action, judgments, damages, losses, liabilities, and all costs and expenses of defense, including, without limitation, reasonable attorneys' fees, arising out of or relating to: your breach or alleged breach of your representations; your violation of these Terms; or a claim that is based on your use of the Feeds, your dissemination of any Materials, or any content transmitted by you. You will cooperate as fully and as reasonably required in Company's defense of any claim. Company reserves the right, at its own expense, to assume the exclusive defense and control of any matter subject to indemnification by you, and you will not in any event settle any matter without the written consent of Company.</p>
			<h4 class="legal__sub-headline">VIII. LOCATION</h4>
			<p class="legal__body">These Feeds are operated in the United States. These Terms are specifically not governed by the United Nations Conventions on Contracts for the International Sale of Goods, if otherwise applicable. These Terms will be interpreted, construed, governed and enforced solely by and in accordance with the Laws of the State of New York, as it is applied to agreements entered into and to be performed entirely within New York. You agree that any suit you bring regarding the Feeds, the Materials, or these Terms will be brought in the state or federal courts located in New York County, New York, and you agree to submit to the personal jurisdiction of those courts. Any cause of action brought by you with respect to the Terms or your use of these Feeds or Materials must be filed within ninety (90) days after the occurrence of the facts giving rise to the cause of action, otherwise the cause will be forever barred.</p>
			<h4 class="legal__sub-headline">IX. COMPLIANCE WITH LAWS</h4>
			<p class="legal__body">You agree to comply with all rules, laws and regulations that are applicable to your use of the Feeds and the Materials, including, without limitation, all applicable laws, rules and regulations governing your transmission or use of any software or data. If any provision of these Terms is unenforceable in whole or in part, the remaining Terms will not be affected.</p>
			<h4 class="legal__sub-headline">X. VIOLATION AND ADDITIONAL POLICIES</h4>
			<p class="legal__body">Company will determine your compliance with these Terms in its sole discretion. Any violation of these Terms may result in restrictions on your access to all or part of the Feeds. No waiver of any of these Terms by Company will be of any force or effect unless made in writing and signed by a duly authorized officer of Company. Company reserves the right to modify or discontinue these Feeds or any portion thereof without notice to you or any third party. You are advised that Company will aggressively enforce its rights to the fullest extent of the law, including, without limitation, the seeking of criminal prosecution or injunctive relief against you. No waiver by Company of any breach of any term or provision of these Terms will be construed as a waiver of any preceding or succeeding breach of the same or of any other term or provision.</p>
			<h4 class="legal__sub-headline">XI. CONTACT INFORMATION</h4>
			<p class="legal__body">If you have any questions or concerns regarding these Terms, please visit <a class="legal__body__link" href="https://www.sho.com/network-feed/home">www.sho.com/network-feed/home</a> or write to us at Showtime Networks Inc., 1633 Broadway, New York, NY 10019, Attn: Marketing</p>
			<h4 class="legal__sub-headline">XII. CHANGES</h4>
			<p class="legal__body">Company reserves the right in its sole discretion to modify, alter or otherwise revise these Terms.</p>
			<p class="legal__body">THE EFFECTIVE DATE OF THESE TERMS OF USE IS NOVEMBER 29, 2018.</p>
  	</section>
  {{/content}}

	{{$footer}}
		<footer class="footer" data-context="footer">
			{{> partials/_footer_nav }}
		</footer>
	{{/footer}}

{{/layouts/default}}
